package com.vishvendra.procart.entities;

public enum AuditAction {
  ADD_PRODUCT,
  UPDATE_PRODUCT,
  DELETE_PRODUCT,
  UPDATE_INVENTORY,
  CREATE_INVENTORY,
  CREATE_CART,
  CART_UPDATE,
  CART_COMPLETE,
  CURRENCY_ADDED,
  CURRENCY_UPDATED,
  ASSOCIATE_CHARGE,
  ADMIN_CREATED,
  USER_REGISTERED,
  CREATE_CHARGE,
  CURRENCY_DELETED;
}
